In [14]:
import pandas as pd 
import matplotlib.pyplot as plt
import datetime as dt 
import seaborn as sns 
import numpy as np

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix

In [15]:
df = pd.read_csv('base_data/Spotify_Song_Attributes.csv')
view = pd.concat([df.head(), df.tail()])

view

trackName  \
0                                               "Honest"   
1      "In The Hall Of The Mountain King" from Peer G...   
2                                     #BrooklynBloodPop!   
3                                                    $10   
4                             (I Just) Died In Your Arms   
10075                                 Younger with Time.   
10076                Your Latest Trick - Remastered 1996   
10077                Your Love Is My Drug (8 Bit Slowed)   
10078                                         Your Power   
10079                            Your Voice / Bethel, NY   

                      artistName  msPlayed              genre  danceability  \
0                   Nico Collins    191772                NaN         0.476   
1      London Symphony Orchestra   1806234  british orchestra         0.475   
2                           SyKo    145610         glitchcore         0.691   
3                   Good Morning     25058   experimental pop         0.624   
4                   Cutting Crew   5504949         album rock         0.625   
10075                  Ben Zaidi    668478           folk-pop         0.537   
10076               Dire Straits    304382                NaN           NaN   
10077                just valery     97600          sad lo-fi         0.282   
10078              Billie Eilish    988224            art pop         0.632   
10079                      Jaden    213626            pop rap         0.560   

       energy   key  loudness  mode  speechiness  ...  liveness  valence  \
0       0.799   4.0    -4.939   0.0       0.2120  ...    0.2570    0.577   
1       0.130   7.0   -17.719   1.0       0.0510  ...    0.1010    0.122   
2       0.814   1.0    -3.788   0.0       0.1170  ...    0.3660    0.509   
3       0.596   4.0    -9.804   1.0       0.0314  ...    0.1190    0.896   
4       0.726  11.0   -11.402   0.0       0.0444  ...    0.0625    0.507   
10075   0.143   2.0   -16.992   1.0       0.0331  ...    0.1100    0.245   
10076     NaN   NaN       NaN   NaN          NaN  ...       NaN      NaN   
10077   0.158   6.0    -7.783   1.0       0.0311  ...    0.4740    0.248   
10078   0.284   9.0   -14.025   0.0       0.0801  ...    0.2330    0.208   
10079   0.344   3.0   -12.283   1.0       0.0306  ...    0.1110    0.428   

         tempo            type                      id  \
0      162.139  audio_features  7dTxqsaFGHOXwtzHINjfHv   
1      112.241  audio_features  14Qcrx6Dfjvcj0H8oV8oUW   
2      132.012  audio_features  7K9Z3yFNNLv5kwTjQYGjnu   
3      120.969  audio_features  3koAwrM1RO0TGMeQJ3qt9J   
4      124.945  audio_features  4ByEFOBuLXpCqvO1kw8Wdm   
10075  131.118  audio_features  6o8pM5reLgjd5i8gDY3Irt   
10076      NaN             NaN                     NaN   
10077   65.152  audio_features  1EoThnDm6kQfB2idIfR30n   
10078  129.642  audio_features  042Sl6Mn83JHyLEqdK7uI0   
10079  115.393  audio_features  3BcN2Pcy0kTG1zm8Tz9MsB   

                                        uri  \
0      spotify:track:7dTxqsaFGHOXwtzHINjfHv   
1      spotify:track:14Qcrx6Dfjvcj0H8oV8oUW   
2      spotify:track:7K9Z3yFNNLv5kwTjQYGjnu   
3      spotify:track:3koAwrM1RO0TGMeQJ3qt9J   
4      spotify:track:4ByEFOBuLXpCqvO1kw8Wdm   
10075  spotify:track:6o8pM5reLgjd5i8gDY3Irt   
10076                                   NaN   
10077  spotify:track:1EoThnDm6kQfB2idIfR30n   
10078  spotify:track:042Sl6Mn83JHyLEqdK7uI0   
10079  spotify:track:3BcN2Pcy0kTG1zm8Tz9MsB   

                                              track_href  \
0      https://api.spotify.com/v1/tracks/7dTxqsaFGHOX...   
1      https://api.spotify.com/v1/tracks/14Qcrx6Dfjvc...   
2      https://api.spotify.com/v1/tracks/7K9Z3yFNNLv5...   
3      https://api.spotify.com/v1/tracks/3koAwrM1RO0T...   
4      https://api.spotify.com/v1/tracks/4ByEFOBuLXpC...   
10075  https://api.spotify.com/v1/tracks/6o8pM5reLgjd...   
10076                                                NaN   
10077  https://api.spotify.com/v1/tracks/1

In [29]:
sk = df['artistName'].str.contains('SyKo')

In [ ]:
df.isnull().sum()

trackName              0
artistName             0
msPlayed               0
genre               1500
danceability         550
energy               550
key                  550
loudness             550
mode                 550
speechiness          550
acousticness         550
instrumentalness     550
liveness             550
valence              550
tempo                550
type                 550
id                   550
uri                  550
track_href           550
analysis_url         550
duration_ms          550
time_signature       550
dtype: int64

In [ ]:
df = df.dropna()

df.isnull().sum()

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8580 entries, 1 to 10079
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   trackName         8580 non-null   object 
 1   artistName        8580 non-null   object 
 2   msPlayed          8580 non-null   int64  
 3   genre             8580 non-null   object 
 4   danceability      8580 non-null   float64
 5   energy            8580 non-null   float64
 6   key               8580 non-null   float64
 7   loudness          8580 non-null   float64
 8   mode              8580 non-null   float64
 9   speechiness       8580 non-null   float64
 10  acousticness      8580 non-null   float64
 11  instrumentalness  8580 non-null   float64
 12  liveness          8580 non-null   float64
 13  valence           8580 non-null   float64
 14  tempo             8580 non-null   float64
 15  type              8580 non-null   object 
 16  id                8580 non-null   object 

In [ ]:
X = df[["danceability", "energy", "loudness", "liveness"]].values 
y = df[["genre"]].values 

label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y.ravel())

#Sepliting my test
X_test, X_train, y_test, y_train = train_test_split(X, y, test_size=.3, random_state=42, stratify=y)

knn = KNeighborsClassifier(n_neighbors=15)

knn.fit(X_train, y_train)
predict = knn.predict(X_test)

predicted_labels = label_encoder.inverse_transform(predict)

df_test_predicted = pd.DataFrame(X_test, columns=["danceability", "energy", "loudness", "liveness"])
df_test_predicted["predicted_genre"] = predicted_labels 

df_test_predicted

danceability  energy  loudness  liveness      predicted_genre
0            0.186  0.6790    -7.884    0.1280                filmi
1            0.468  0.2470   -10.090    0.1010                alt z
2            0.359  0.4480   -13.081    0.1630         ambient folk
3            0.619  0.0936   -16.143    0.0825          lo-fi sleep
4            0.508  0.9710    -3.027    0.6200                filmi
...            ...     ...       ...       ...                  ...
6001         0.487  0.7040    -5.825    0.0686        electro house
6002         0.590  0.7790    -5.574    0.1020                  pop
6003         0.447  0.7810    -3.469    0.2040  alternative hip hop
6004         0.796  0.6810    -6.067    0.1050                  pop
6005         0.636  0.6480    -4.477    0.2310         desi hip hop

[6006 rows x 5 columns]

In [ ]:
round(knn.score(X_test, y_test)*100, 2)

11.51

In [ ]:
print(confusion_matrix(y_test, predict))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
